Comment out previous Python package build and deployment steps in CI workflow, and update Docker image tags to use 'blooo-io'

diff --git a/.github/workflows/continuous-integration-workflow.yml b/.github/workflows/continuous-integration-workflow.yml
--- a/.github/workflows/continuous-integration-workflow.yml
+++ b/.github/workflows/continuous-integration-workflow.yml
@@ -86,54 +86,54 @@ jobs:
         make -C build/ test
         pytest
 
-  package_python:
-    name: Build and deploy Speculos Python Package
-    runs-on: public-ledgerhq-shared-small
-    needs: [build]
-    permissions:
-      id-token: write
-      attestations: write
-      contents: write
-    container:
-      image: docker://ghcr.io/ledgerhq/speculos-builder:latest
+  # package_python:
+  #   name: Build and deploy Speculos Python Package
+  #   runs-on: public-ledgerhq-shared-small
+  #   needs: [build]
+  #   permissions:
+  #     id-token: write
+  #     attestations: write
+  #     contents: write
+  #   container:
+  #     image: docker://ghcr.io/ledgerhq/speculos-builder:latest
 
-    steps:
-    - name: Clone
-      uses: actions/checkout@v4
-      with:
-        fetch-depth: 0
+  #   steps:
+  #   - name: Clone
+  #     uses: actions/checkout@v4
+  #     with:
+  #       fetch-depth: 0
 
-    - name: Use pip to install Speculos in a virtual environment
-      run: |
-        python3 -m venv venv-test
-        ./venv-test/bin/pip install .
-        ./venv-test/bin/speculos --help
-        echo "TAG_VERSION=$(./venv-test/bin/python -c 'from speculos import __version__; print(__version__)')" >> "$GITHUB_ENV"
+  #   - name: Use pip to install Speculos in a virtual environment
+  #     run: |
+  #       python3 -m venv venv-test
+  #       ./venv-test/bin/pip install .
+  #       ./venv-test/bin/speculos --help
+  #       echo "TAG_VERSION=$(./venv-test/bin/python -c 'from speculos import __version__; print(__version__)')" >> "$GITHUB_ENV"
 
-    - name: Build Speculos python package
-      run: |
-        git config --global --add safe.directory "$GITHUB_WORKSPACE"
-        if [ -e dist ] ; then
-          echo >&2 "Error: dist/ directory already exists and this is unexpected. Refusing to build new packages."
-          exit 1
-        fi
-        python3 -m venv venv-build
-        ./venv-build/bin/pip install --upgrade pip build twine
-        ./venv-build/bin/python -m build
-        ./venv-build/bin/python -m twine check dist/*
+  #   - name: Build Speculos python package
+  #     run: |
+  #       git config --global --add safe.directory "$GITHUB_WORKSPACE"
+  #       if [ -e dist ] ; then
+  #         echo >&2 "Error: dist/ directory already exists and this is unexpected. Refusing to build new packages."
+  #         exit 1
+  #       fi
+  #       python3 -m venv venv-build
+  #       ./venv-build/bin/pip install --upgrade pip build twine
+  #       ./venv-build/bin/python -m build
+  #       ./venv-build/bin/python -m twine check dist/*
 
-    - name: Check version against CHANGELOG
-      if: success() && github.event_name == 'push' && startsWith(github.ref, 'refs/tags/')
-      shell: bash
-      run: |
-        CHANGELOG_VERSION=$(grep -Po '(?<=## \[)(\d+\.)+[^\]]' CHANGELOG.md | head -n 1)
-        if [ "${{ env.TAG_VERSION }}" == "${CHANGELOG_VERSION}" ]; \
-        then \
-            exit 0; \
-        else \
-            echo "Tag '${{ env.TAG_VERSION }}' and CHANGELOG '${CHANGELOG_VERSION}' versions mismatch!"; \
-            exit 1; \
-        fi
+  #   - name: Check version against CHANGELOG
+  #     if: success() && github.event_name == 'push' && startsWith(github.ref, 'refs/tags/')
+  #     shell: bash
+  #     run: |
+  #       CHANGELOG_VERSION=$(grep -Po '(?<=## \[)(\d+\.)+[^\]]' CHANGELOG.md | head -n 1)
+  #       if [ "${{ env.TAG_VERSION }}" == "${CHANGELOG_VERSION}" ]; \
+  #       then \
+  #           exit 0; \
+  #       else \
+  #           echo "Tag '${{ env.TAG_VERSION }}' and CHANGELOG '${CHANGELOG_VERSION}' versions mismatch!"; \
+  #           exit 1; \
+  #       fi
 
     # - name: Publish Python package on pypi.org
     #   if: success() && github.event_name == 'push' && startsWith(github.ref, 'refs/tags/')
@@ -304,7 +304,7 @@ jobs:
         id: meta
         uses: docker/metadata-action@v4
         with:
-          images: ghcr.io/ledgerhq/speculos
+          images: ghcr.io/blooo-io/speculos
           tags: |
             type=raw,value=${{ github.sha }}
             type=ref,event=branch
